using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ActionController : MonoBehaviour
{
    [SerializeField]
    private float range;  // ì•„ì´í…œ ìŠµë“ì´ ê°€ëŠ¥í•œ ìµœëŒ€ ê±°ë¦¬
    private bool pickupActivated = false;  // ì•„ì´í…œ ìŠµë“ ê°€ëŠ¥í• ì‹œ True 
    private bool dissolveActivated = false; // ê³ ê¸° í•´ì²´ ê°€ëŠ¥í•  ì‹œ True (ë¼ì§€ ì‹œì²´ë¥¼ ë°”ë¼ ë³¼ ë•Œ)
    private bool isDissolving = false;  // ê³ ê¸° í•´ì²´ ì¤‘ì¼ ë•Œ True (ì¤‘ë³µí•´ì„œ í•´ì²´í•˜ì§€ ì•Šë„ë¡)
    private bool firedLookActivated = false; // ë¶ˆì— ì ‘ê·¼í•´ì„œ ë¶ˆì„ ë°”ë¼ë³¼ ì‹œ True
    private bool lookComputer = false; // ì»´í“¨í„°ë¥¼ ë°”ë¼ë³¼ ì‹œ true
    private bool lookArchemyTable = false;
    
    [SerializeField]
    private Transform tf_MeatDissolveTool;  // ê³ ê¸° í•´ì²´ ì†. ì¦‰ Meat Knife. ê³ ê¸° í•´ì²´í•  ë•Œ í™œì„±í™” í•´ì•¼ í•¨
    private RaycastHit hitInfo;  // ì¶©ëŒì²´ ì •ë³´ ì €ì¥
    [SerializeField]
    private LayerMask layerMask;  // íŠ¹ì • ë ˆì´ì–´ë¥¼ ê°€ì§„ ì˜¤ë¸Œì íŠ¸ì— ëŒ€í•´ì„œë§Œ ìŠµë“í•  ìˆ˜ ìˆì–´ì•¼ í•œë‹¤.
    [SerializeField]
    private string sound_meat; // ê³ ê¸° í•´ì²´ ì†Œë¦¬

    [SerializeField]
    private Text actionText;  // í–‰ë™ì„ ë³´ì—¬ ì¤„ í…ìŠ¤íŠ¸
    [SerializeField]
    private Text itemFullText;  // ì•„ì´í…œì´ ê½‰ ì°¼ë‹¤ëŠ” ê²½ê³  ë©”ì„¸ì§€ë¥¼ ë³´ì—¬ì¤„ í…ìŠ¤íŠ¸
    [SerializeField]
    private Inventory theInventory;  // ğŸ“œInventory.cs

    [SerializeField]
    private QuickSlotController theQuickSlotController; // ğŸ“œQuickSlotController.cs
    [SerializeField] private ComputerKit theComputer; // ğŸ“œComputerKit.cs


    void Update()
    {
        CheckAction();// ê³ ê¸° or ì•„ì´í…œ ì•¡ì…˜ í…ìŠ¤íŠ¸ ë„ìš°ê¸° ì‹œë„
        TryAction();
    }

    private void CheckAction()
    {
        if (Physics.Raycast(transform.position, transform.forward, out hitInfo, range, layerMask))
        {
            if (hitInfo.transform.tag == "Item")
                ItemInfoAppear();
            else if (hitInfo.transform.tag == "Weak_Animal")
                MeatInfoAppear();
            else if (hitInfo.transform.tag == "Fire")
                FireInfoAppear();
            else if (hitInfo.transform.tag == "Computer")
                ComputerInfoAppear();
            else if (hitInfo.transform.tag == "ArchemyTable")
                ArchemyInfoAppear();
            else
                InfoDisappear();
        }
        else
            InfoDisappear();
    }

    private void TryAction()
    {
        if(Input.GetKeyDown(KeyCode.E))  // E í‚¤ ì…ë ¥ì´ ë“¤ì–´ ì˜¤ë©´ 
        {
            CheckAction();   // ê³ ê¸° or ì•„ì´í…œ ì•¡ì…˜ í…ìŠ¤íŠ¸ ë„ìš°ê¸° ì‹œë„
            CanPickUp();  // ì•„ì´í…œì„ ì£¼ìš¸ ìˆ˜ ìˆëŠ”ì§€ 
            CanMeat();  // ê³ ê¸°ë¥¼ ì£¼ìš¸ ìˆ˜ ìˆëŠ”ì§€
            CanDropFire();
            CanComputerPowerOn();
            CanArchemyTableOpen();
        }
    }
    
    private void CheckItem()
    {
        if (Physics.Raycast(transform.position, transform.forward, out hitInfo, range, layerMask))
        {
            if (hitInfo.transform.tag == "Item")
            {
                ItemInfoAppear();
            }
        }
        else
            ItemInfoDisappear();
    }

    private void ArchemyInfoAppear()
    {
        if (!hitInfo.transform.GetComponent<ArchemyTable>().GetIsOpen())
        {
            Reset();
            lookArchemyTable = true;
            actionText.gameObject.SetActive(true);
            actionText.text = "ì—°ê¸ˆ í…Œì´ë¸” ì¡°ì‘ " + "<color=yellow>" + "(E)" + "</color>";
        }
    }
    private void CanArchemyTableOpen()
    {
        if (lookArchemyTable)
        {
            if (hitInfo.transform != null)
            {
                hitInfo.transform.GetComponent<ArchemyTable>().Window();
                InfoDisappear();
            }
        }
    }

    private void ItemInfoAppear()
    {
        Reset();
        pickupActivated = true;
        actionText.gameObject.SetActive(true);
        actionText.text = hitInfo.transform.GetComponent<ItemPickUp>().item.itemName + " íšë“ " + "<color=yellow>" + "(E)" + "</color>";
    }

    private void ItemInfoDisappear()
    {
        pickupActivated = false;
        dissolveActivated = false;
        firedLookActivated = false;
        lookComputer = false;
        actionText.gameObject.SetActive(false);
    }

    private void ComputerInfoAppear()
    {
        if (!hitInfo.transform.GetComponent<ComputerKit>().isPowerOn)
        {
            Reset();
            lookComputer = true;
            actionText.gameObject.SetActive(true);
            actionText.text = "ì»´í“¨í„° ê°€ë™ " + "<color=yellow>" + "(E)" + "</color>";
        }
    }

    private void CanComputerPowerOn()
    {
        if (lookComputer)
        {
            if (hitInfo.transform != null)
            {
                if (!hitInfo.transform.GetComponent<ComputerKit>().isPowerOn)
                {
                    hitInfo.transform.GetComponent<ComputerKit>().PowerOn();
                    InfoDisappear();
                }
            }
        }
    }

    private void CanPickUp()
    {
        if(pickupActivated)
        {
            if(hitInfo.transform != null)
            {
                Debug.Log(hitInfo.transform.GetComponent<ItemPickUp>().item.itemName + " íšë“ í–ˆìŠµë‹ˆë‹¤.");
                theInventory.AcquireItem(hitInfo.transform.GetComponent<ItemPickUp>().item);
                Destroy(hitInfo.transform.gameObject);
                InfoDisappear();
            }
        }
    }

    public IEnumerator WhenInventoryIsFull()
    {
        itemFullText.gameObject.SetActive(true);
        itemFullText.text = "ì•„ì´í…œì´ ê½‰ ì°¼ìŠµë‹ˆë‹¤.";

        yield return new WaitForSeconds(3.0f);  // 3 ì´ˆ í›„ ë©”ì„¸ì§€ëŠ” ì‚¬ë¼ì§. ë©”ì„¸ì§€ëŠ” 3 ì´ˆë§Œ ë„ì›€.
        itemFullText.gameObject.SetActive(false);
    }

    private void Reset()
    {
        pickupActivated = false;
        dissolveActivated = false;
        firedLookActivated = false;
    }


    private void MeatInfoAppear()
    {
        if (hitInfo.transform.GetComponent<Animal>().isDead) // ì£½ì€ ë¼ì§€ë¥¼ ë°”ë¼ë´¤ì„ ê²½ìš°ì—ë§Œ (ì¹´ë©”ë¼ì—ì„œ ìœ Raycastê°€ ì£½ì€ ë¼ì§€ì™€ ì¶©ëŒ)
        {
            Reset();
            dissolveActivated = true;
            actionText.gameObject.SetActive(true);
            actionText.text = hitInfo.transform.GetComponent<Animal>().animalName + " í•´ì²´í•˜ê¸° " + "<color=yellow>" + "(E)" + "</color>";
        }
    }

    private void FireInfoAppear()
    {
        Reset();
        firedLookActivated = true;
        
        if (hitInfo.transform.GetComponent<Fire>().GetIsFire())
        {
            actionText.gameObject.SetActive(true);
            actionText.text = "ì„ íƒëœ ì•„ì´í…œ ë¶ˆì— ë„£ê¸°" + "<color=yellow>" + "(E)" + "</color>";
        }
    }

    private void InfoDisappear()
    {
        pickupActivated = false;
        dissolveActivated = false;
        firedLookActivated = false;
        lookComputer = false;
        actionText.gameObject.SetActive(false);
    }

    IEnumerator MeatCoroutine()
    {
        WeaponManager.isChangeWeapon = true;  // ê³ ê¸° í•´ì²´ ì¤‘ì— ë¬´ê¸°ê°€ êµì²´ë˜ì§€ ì•Šë„ë¡
        WeaponSway.isActivated = false;

        // ë“¤ê³  ìˆë˜ ë¬´ê¸° ë¹„í™œ
        WeaponManager.currentWeaponAnim.SetTrigger("Weapon_Out");
        PlayerController.isActivated = false;
        yield return new WaitForSeconds(0.2f);  // ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ í›„ ë¹„í™œë˜ë„ë¡
        WeaponManager.currentWeapon.gameObject.SetActive(false);

        // ì¹¼ êº¼ë‚´ê¸°
        tf_MeatDissolveTool.gameObject.SetActive(true);  // ì• ë‹ˆë©”ì´ì…˜ì€ ì´ë•Œ ìë™ìœ¼ë¡œ ì‹¤í–‰ë¨ (ë””í´íŠ¸ìƒíƒœë‹ˆê¹Œ)
        yield return new WaitForSeconds(0.2f);  // ì• ë‹ˆë©”ì´ì…˜ 0.2ì´ˆ ì§„í–‰ í›„
        SoundManager.instance.PlaySE(sound_meat);  // ê³ ê¸° í•´ì²´ ì†Œë¦¬
        yield return new WaitForSeconds(1.8f);  // ì¹¼ í•´ì²´í•˜ëŠ” ì• ë‹ˆë©”ì´ì…˜ ë‹¤ ëë‚˜ê¸¸ ê¸°ë‹¤ë¦¼

        // ê³ ê¸° ì•„ì´í…œ ì–»ê¸°
        theInventory.AcquireItem(hitInfo.transform.GetComponent<WeakAnimal>().GetItem(), hitInfo.transform.GetComponent<WeakAnimal>().itemNumber);

        // ì¹¼ í•´ì²´ ì†ì€ ì§‘ì–´ ë„£ê³  ë‹¤ì‹œ ì›ë˜ ë¬´ê¸°ë¡œ
        WeaponManager.currentWeapon.gameObject.SetActive(true);
        tf_MeatDissolveTool.gameObject.SetActive(false);

        PlayerController.isActivated = true;
        WeaponSway.isActivated = true;
        WeaponManager.isChangeWeapon = false;  // ë‹¤ì‹œ ë¬´ê¸° êµì²´ê°€ ê°€ëŠ¥í•˜ë„ë¡
        isDissolving = false;
    }

    private void CanMeat()
    {
        if  (dissolveActivated)
        {
            if (hitInfo.transform.tag == "Weak_Animal" && hitInfo.transform.GetComponent<Animal>().isDead && !isDissolving)
            {
                isDissolving = true;
                InfoDisappear();
                
                StartCoroutine(MeatCoroutine()); // ê³ ê¸° í•´ì²´ ì‹¤ì‹œ
            }
        }
    }

    private void CanDropFire()
    {
        if (firedLookActivated)
        {
            if (hitInfo.transform.tag == "Fire" && hitInfo.transform.GetComponent<Fire>().GetIsFire())
            {
                // ì†ì— ë“¤ê³  ìˆëŠ” ì•„ì´í…œì„ ë¶ˆì— ë„£ìŒ <- ì„ íƒëœ í€µìŠ¬ë¡¯ì˜ ì•„ì´í…œì„ ë„£ìŒ (Null ë¹ˆìŠ¬ë¡¯ì¼ ìˆ˜ë„ ìˆìŒ. íŒë³„ì´ í•„ìš”)
                Slot _selectedSlot = theQuickSlotController.GetSelectedSlot();

                if (_selectedSlot.item != null)
                    DropAnItem(_selectedSlot);
            }
        }
    }

    private void DropAnItem(Slot _selectedSlot)
    {
        switch(_selectedSlot.item.itemType)
        {
            case Item.ItemType.Used:
                if (_selectedSlot.item.itemName.Contains("ê³ ê¸°"))
                {
                    Instantiate(_selectedSlot.item.itemPrefab, hitInfo.transform.position + Vector3.up, Quaternion.identity);
                    theQuickSlotController.DecreaseSelectedItem();
                }
                break;
            case Item.ItemType.Ingredient:
                break;
        }
    }
}
