using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
// ìŠ¤í”¼ë“œ ì¡°ì • ë³€ìˆ˜
    [SerializeField]
    private float walkSpeed;
    [SerializeField]
    private float runSpeed;
    [SerializeField]
    private float crouchSpeed;
    private float applySpeed; //ìƒí™©ì— ë”°ë¼ ê°ê°ì˜ Speedë¥¼ ì ìš©

    // ì í”„ ì •ë„
    [SerializeField]
    private float jumpForce;

    // ìƒíƒœ ë³€ìˆ˜
    private bool isRun = false; public bool GetRun(){return isRun;}
    private bool isGround = true;
    private bool isCrouch = false;
    private bool isWalk = false; 
    private bool pauseCameraRotation = false;
    static public bool isActivated = true;

    // ì•‰ì•˜ì„ ë•Œ ì–¼ë§ˆë‚˜ ì•‰ì„ì§€ ê²°ì •í•˜ëŠ” ë³€ìˆ˜
    [SerializeField]
    private float crouchPosY;
    private float originPosY;
    private float applyCrouchPosY;

    // ì „ í”„ë ˆì„ì˜ ìœ„ì¹˜. í˜„ì¬ í”„ë ˆì„ì˜ ìœ„ì¹˜ì™€ ë¹„êµí–ˆì„ ë•Œ ë‹¬ë¼ì§€ë©´ ì›€ì§ì„ì´ ìˆì—ˆë˜ ê²ƒì´ë‹¤.
    private Vector3 lastPos;  
    private Crosshair theCrosshair;

    // ë¯¼ê°ë„
    [SerializeField]
    private float lookSensitivity;  

    // ì¹´ë©”ë¼ í•œê³„
    [SerializeField]
    private float cameraRotationLimit;  
    private float currentCameraRotationX; 

    // í•„ìš”í•œ ì»´í¬ë„ŒíŠ¸
    [SerializeField]
    private Camera theCamera; 
    private Rigidbody myRigid;
    private CapsuleCollider capsuleCollider; 
    private GunController theGunController;
    private StatusController theStatusController;

    void Start() 
    {
        // ì»´í¬ë„ŒíŠ¸ í• ë‹¹
        capsuleCollider = GetComponent<CapsuleCollider>();
        myRigid = GetComponent<Rigidbody>();
        theGunController = FindObjectOfType<GunController>();
        theCrosshair = FindObjectOfType<Crosshair>();
        theStatusController = FindObjectOfType<StatusController>();

        // ì´ˆê¸°í™”
        applySpeed = walkSpeed;
        originPosY = theCamera.transform.localPosition.y;
        applyCrouchPosY = originPosY;
    }

    void Update()
    {
        if (isActivated && GameManager.canPlayerMove)
        {
            IsGround();
            TryJump();
            TryRun();
            TryCrouch();
            Move();
            MoveCheck();
            CameraRotation();
            CharacterRotation();
        }
    }

    // ì§€ë©´ ì²´í¬
    private void IsGround()
    {
        //í˜„ì¬ ìœ„ì¹˜ì—ì„œ ì ˆëŒ€ì ì¸ ì›”ë“œ ì¢Œí‘œê³„ ê¸°ì¤€ ì•„ë˜ë¡œ ê´‘ì„ ì„ ìˆì„ ë•Œ ì¶©ëŒì´ ê°ì§€ëœë‹¤ë©´
        isGround = Physics.Raycast(transform.position, Vector3.down, capsuleCollider.bounds.extents.y + 0.1f);
        theCrosshair.JumpingAnimation(!isGround);
    }

    // ì í”„ ì‹œë„
    private void TryJump()
    {
        if (Input.GetKeyDown(KeyCode.Space) && isGround && theStatusController.GetCurrentSP() > 0)
        {
            Jump();
        }
    }

    // ì í”„
    private void Jump()
    {
        if (isCrouch)
            Crouch();

        theStatusController.DecreaseStamina(100);
        myRigid.velocity = transform.up * jumpForce;
    }

    // ë‹¬ë¦¬ê¸° ì‹œë„ - ì™¼ìª½ ì‰¬í”„íŠ¸í‚¤
    private void TryRun()
    {
        if (Input.GetKey(KeyCode.LeftShift) && theStatusController.GetCurrentSP() > 0)
        {
            Running();
        }
        if (Input.GetKeyUp(KeyCode.LeftShift) || theStatusController.GetCurrentSP() <= 0)
        {
            RunningCancel();
        }
    }

    // ë‹¬ë¦¬ê¸°
    private void Running()
    {
        if (isCrouch)
            Crouch();

        theGunController.CancelFineSight(); //ë›¸ ë•ŒëŠ” ì •ì¡°ì¤€ í•´ì œ
        isRun = true;
        theCrosshair.RunningAnimation(isRun);
        theStatusController.DecreaseStamina(10);
        applySpeed = runSpeed;
    }

    // ë‹¬ë¦¬ê¸° ì·¨ì†Œ
    private void RunningCancel()
    {
        isRun = false;
        theCrosshair.RunningAnimation(isRun);
        applySpeed = walkSpeed;
    }

    // ì•‰ê¸° ì‹œë„
    private void TryCrouch()
    {
        if (Input.GetKeyDown(KeyCode.LeftControl))
        {
            Crouch();
        }
    }

    // ì•‰ê¸° ë™ì‘ - ì¹´ë©”ë¼ ìœ„ì¹˜ë§Œ ë‚´ë ¤ì¤€ë‹¤
    private void Crouch()
    {
        isCrouch = !isCrouch;
        theCrosshair.CrouchingAnimation(isCrouch);
        if (isCrouch)
        {
            applySpeed = crouchSpeed;
            applyCrouchPosY = crouchPosY;
        }
        else
        {
            applySpeed = walkSpeed;
            applyCrouchPosY = originPosY;
        }

        StartCoroutine(CrouchCoroutine());
    }

    // ë¶€ë“œëŸ¬ìš´ ì•‰ê¸° ë™ì‘
    IEnumerator CrouchCoroutine()
    {
        float _posY = theCamera.transform.localPosition.y;
        int count = 0;

        while(_posY != applyCrouchPosY)
        {
            count++;
            _posY = Mathf.Lerp(_posY, applyCrouchPosY, 0.2f);
            theCamera.transform.localPosition = new Vector3(0, _posY, 0);
            if(count > 15)
                break;
            yield return null;
        }
        theCamera.transform.localPosition = new Vector3(0, applyCrouchPosY, 0);
    }

    private void Move()
    {
        float _moveDirX = Input.GetAxisRaw("Horizontal");  
        float _moveDirZ = Input.GetAxisRaw("Vertical");  
        Vector3 _moveHorizontal = transform.right * _moveDirX; 
        Vector3 _moveVertical = transform.forward * _moveDirZ; 

        Vector3 _velocity = (_moveHorizontal + _moveVertical).normalized * applySpeed; 

        myRigid.MovePosition(transform.position + _velocity * Time.deltaTime);
    }

    private void CameraRotation()  
    {
        if (!pauseCameraRotation)
        {
            float _xRotation = Input.GetAxisRaw("Mouse Y"); 
            float _cameraRotationX = _xRotation * lookSensitivity;

            // currentCameraRotationX += _cameraRotationX;  ë§ˆìš°ìŠ¤ Y ë°˜ì „
            currentCameraRotationX -= _cameraRotationX;
            //currentCameraRotationX ê°€ (-cameraRotationLimit ~ cameraRotationLimit) ë²”ìœ„ ì•ˆì—ë§Œ ìˆë„ë¡
            currentCameraRotationX = Mathf.Clamp(currentCameraRotationX, -cameraRotationLimit, cameraRotationLimit);

            theCamera.transform.localEulerAngles = new Vector3(currentCameraRotationX, 0f, 0f);
        }
    }

    public IEnumerator TreeLookCoroutine(Vector3 _target)
    {
        pauseCameraRotation = true;

        Quaternion direction = Quaternion.LookRotation(_target - theCamera.transform.position);
        Vector3 eulerValue = direction.eulerAngles;
        float destinationX = eulerValue.x;

        while(Mathf.Abs(destinationX - currentCameraRotationX) >= 0.5f)
        {
            eulerValue = Quaternion.Lerp(theCamera.transform.localRotation, direction, 0.3f).eulerAngles;  // ì¿¼í„°ë‹ˆì–¸ ğŸ‘‰ ë²¡í„°
            theCamera.transform.localRotation = Quaternion.Euler(eulerValue.x, 0f, 0f); // ë²¡í„° ğŸ‘‰ ì¿¼í„°ë‹ˆì–¸ (Xì¶•ìœ¼ë¡œë§Œ íšŒì „í•˜ë©´ ë¨)
            currentCameraRotationX = theCamera.transform.localEulerAngles.x; 
            yield return null;
        }
        pauseCameraRotation = false;
    }

    private void MoveCheck()
    {
        if (!isRun && !isCrouch && isGround)
        {
            if (Vector3.Distance(lastPos, transform.position) >= 0.01f)
                isWalk = true;
            else
                isWalk = false;

            theCrosshair.WalkingAnimation(isWalk);
            lastPos = transform.position;
        }  
    }

    private void CharacterRotation()  // ì¢Œìš° ìºë¦­í„° íšŒì „
    {
        float _yRotation = Input.GetAxisRaw("Mouse X");
        Vector3 _characterRotationY = new Vector3(0f, _yRotation, 0f) * lookSensitivity;
        //ë‘ ì¿¼í„°ë‹ˆì–¸ì˜ íšŒì „ëŸ‰ì„ ë”í•˜ë ¤ë©´ ì„œë¡œ ê³±í•´ì•¼í•œë‹¤.
        myRigid.MoveRotation(myRigid.rotation * Quaternion.Euler(_characterRotationY));
        // Debug.Log(myRigid.rotation);  // ì¿¼í„°ë‹ˆì–¸
        // Debug.Log(myRigid.rotation.eulerAngles); // ë²¡í„°
    }
}