using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// ìë™ìœ¼ë¡œ ì´ ìŠ¤í¬ë¦½íŠ¸ê°€ í™œì„±í™”ë˜ë©´ GunController.cs ê°€ ì»´í¬ë„ŒíŠ¸ë¡œ ë¶™ê²Œ ëœë‹¤.
//ì‹¤ìˆ˜ ë°©ì§€(GunController.csê°€ í•„ìš”í•˜ë‹¤ê³  ê°•ì œ)
[RequireComponent(typeof(GunController))]       
public class WeaponManager : MonoBehaviour
{
    //ë¬´ê¸°ì˜ ì¢…ë¥˜ê°€ ì–´ë–¤ ê²ƒì´ë“ (Gun,Hand...) ëª¨ë“  ë¬´ê¸°ë“¤ì´ í˜„ì¬ êµì²´ì¤‘ì¸ì§€ ì•Œì•„ì•¼ í•œë‹¤.
    public static bool isChangeWeapon = false; //ë¬´ê¸° êµì²´ ì¤‘ì¸ì§€(ì¤‘ë³µì‹¤í–‰ ë°©ì§€-Trueë©´ ëª»í•˜ê²Œ)

    [SerializeField]
    private float changeweaponDelayTime;  //ë¬´ê¸° êµì²´ ë”œë ˆì´ ì‹œê°„. ëŒ€ëµ Weapon_Out ì• ë‹ˆë©”ì´ì…˜ ì‹œê°„.
    [SerializeField]
    private float changeweaponEndDelayTime;  //ë¬´ê¸° êµì²´ê°€ ì™„ì „íˆ ëë‚œ ì‹œì . ëŒ€ëµ Weapon_In ì• ë‹ˆë©”ì´ì…˜ ì‹œê°„.

    [SerializeField]
    private Gun[] guns;  //ëª¨ë“  ì¢…ë¥˜ì˜ ì´ì„ ì›ì†Œë¡œ ê°€ì§€ëŠ” ë°°ì—´
    [SerializeField]
    private CloseWeapon[] hands;  //ëª¨ë“  ì¢…ë¥˜ì˜ Hand í˜• ë¬´ê¸°ë¥¼ ê°€ì§€ëŠ” ë°°ì—´
    [SerializeField]
    private CloseWeapon[] axes;  // ë„ë¼ í˜• ë¬´ê¸°ë¥¼ ê°€ì§€ëŠ” ë°°ì—´
    [SerializeField]
    private CloseWeapon[] pickaxes;  // ê³¡ê´­ì´ í˜• ë¬´ê¸°ë¥¼ ê°€ì§€ëŠ” ë°°ì—´

    // ê´€ë¦¬ ì°¨ì›ì—ì„œ ì´ë¦„ìœ¼ë¡œ ì‰½ê²Œ ë¬´ê¸° ì ‘ê·¼ì´ ê°€ëŠ¥í•˜ë„ë¡ Dictionary ìë£Œ êµ¬ì¡° ì‚¬ìš©.
    private Dictionary<string, Gun> gunDictionary = new Dictionary<string, Gun>();
    private Dictionary<string, CloseWeapon> handDictionary = new Dictionary<string, CloseWeapon>();
    private Dictionary<string, CloseWeapon> axeDictionary = new Dictionary<string, CloseWeapon>();
    private Dictionary<string, CloseWeapon> pickaxeDictionary = new Dictionary<string, CloseWeapon>();

    [SerializeField]
    private string currentWeaponType;  //í˜„ì¬ ë¬´ê¸°ì˜ íƒ€ì…
    //ë¬´ê¸°ì˜ ì¢…ë¥˜ì— ìƒê´€ì—†ì´ ëª¨ë‘ Transform ì»´í¬ë„ŒíŠ¸ë¥¼ ê°€ì§€ê³  ìˆë‹¤.
    //Controller.csê°€ ìê¸°ìì‹ (ë˜ëŠ” ìì‹ ì˜ Animator ì»´í¬ë„ŒíŠ¸)ì„ í• ë‹¹
    public static Transform currentWeapon;  //í˜„ì¬ ë¬´ê¸°. ì—¬ëŸ¬ ìŠ¤í¬ë¦½íŠ¸ì—ì„œ í´ë˜ìŠ¤ ì´ë¦„ìœ¼ë¡œ ë°”ë¡œ ì ‘ê·¼
    public static Animator currentWeaponAnim; //í˜„ì¬ ë¬´ê¸°ì˜ ì• ë‹ˆë©”ì´ì…˜. ì—¬ëŸ¬ ìŠ¤í¬ë¦½íŠ¸ì—ì„œ í´ë˜ìŠ¤ ì´ë¦„ìœ¼ë¡œ ë°”ë¡œ ì ‘ê·¼

    //ë¬´ê¸° êµì²´ì‹œ ì–´ë–¤ ë¬´ê¸°ë¥¼ í™œì„±í™”, ë¹„í™œì„±í™” í• ì§€ ì•Œì•„ì•¼ í•œë‹¤.
    [SerializeField]
    private GunController theGunController;  //ì´ ì¼ë• GunController.cs í™œì„±í™”, ì†ì¼ ë• ğŸ“œGunController.cs ë¹„í™œì„±í™” 
    [SerializeField]
    private HandController theHandController; //ì† ì¼ë• HandController.cs í™œì„±í™”, HandController.cs ë¹„í™œì„±í™”
    [SerializeField]
    private AxeController theAxeController; // ë„ë¼ ì¼ë• ğŸ“œAxeController.cs í™œì„±í™”, ë‹¤ë¥¸ ë¬´ê¸°ì¼ ë• ğŸ“œAxeController.cs ë¹„í™œì„±í™”
    [SerializeField]
    private PickaxeController thePickaxeController; // ê³¡ê´­ì´ ì¼ë• ğŸ“œPickaxeController.cs í™œì„±í™”, ë‹¤ë¥¸ ë¬´ê¸°ì¼ ë• ğŸ“œPickaxeController.cs ë¹„í™œì„±í™”

    void Start()
    {
        for (int i = 0; i < guns.Length; i++)
        {
            gunDictionary.Add(guns[i].gunName, guns[i]);
        }
        for (int i = 0; i < hands.Length; i++)
        {
            handDictionary.Add(hands[i].closeWeaponName, hands[i]);
        }
        for (int i = 0; i < axes.Length; i++)
        {
            axeDictionary.Add(axes[i].closeWeaponName, axes[i]);
        }
        for (int i = 0; i < pickaxes.Length; i++)
        {
            pickaxeDictionary.Add(pickaxes[i].closeWeaponName, pickaxes[i]);
        }

        thePickaxeController.CloseWeaponChange(pickaxeDictionary["Pickaxe"]);
    }

    void Update()
    {
        // if(!Inventory.invectoryActivated)
        // {
        //     //ë¬´ê¸° êµì²´ì¤‘ì´ ì•„ë‹ ë•Œë§Œ í‚¤ ì…ë ¥ì„ ë°›ëŠ”ë‹¤
        //     if(!isChangeWeapon)
        //     {
        //         if (Input.GetKeyDown(KeyCode.Alpha1)) // 1 ëˆ„ë¥´ë©´ 'ë§¨ì†'ìœ¼ë¡œ ë¬´ê¸° êµì²´ ì‹¤í–‰
        //         {
        //             StartCoroutine(ChangeWeaponCoroutine("HAND", "ë§¨ì†"));
        //         }
        //         else if (Input.GetKeyDown(KeyCode.Alpha2)) // 2 ëˆ„ë¥´ë©´ 'ì„œë¸Œ ë¨¸ì‹ ê±´'ìœ¼ë¡œ ë¬´ê¸° êµì²´ ì‹¤í–‰
        //         {
        //             StartCoroutine(ChangeWeaponCoroutine("GUN", "SubMachineGun1"));
        //         }
        //         else if (Input.GetKeyDown(KeyCode.Alpha3)) // 3 ëˆ„ë¥´ë©´ 'ë„ë¼'ë¡œ ë¬´ê¸° êµì²´ ì‹¤í–‰
        //             StartCoroutine(ChangeWeaponCoroutine("AXE", "Axe"));
        //         else if (Input.GetKeyDown(KeyCode.Alpha4)) // 4 ëˆ„ë¥´ë©´ 'ê³¡ê´­ì´'ë¡œ ë¬´ê¸° êµì²´ ì‹¤í–‰
        //             StartCoroutine(ChangeWeaponCoroutine("PICKAXE", "Pickaxe"));
        //     }
        // }

    }

    public IEnumerator ChangeWeaponCoroutine(string _type, string _name)
    {
        isChangeWeapon = true;
        currentWeaponAnim.SetTrigger("Weapon_Out"); //ë¬´ê¸° êº¼ë‚´ëŠ” ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ

        yield return new WaitForSeconds(changeweaponDelayTime); //ë¬´ê¸° ë„£ëŠ” ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒí•  ë™ì•ˆ ëŒ€ê¸°

        CancelPreWeaponAction(); //ê¸°ì¡´ì˜ ë¬´ê¸° í•´ì œ
        WeaponChange(_type, _name); //ë°”ê¾¸ê³ ì í•˜ëŠ” ë¬´ê¸°ë¡œ êµì²´

        yield return new WaitForSeconds(changeweaponEndDelayTime); //ë¬´ê¸° êº¼ë‚´ëŠ” ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ ëŒ€ê¸°

        currentWeaponType = _type; //í˜„ì¬ ë¬´ê¸° íƒ€ì… ì—…ë°ì´íŠ¸
        isChangeWeapon = false; //ë¬´ê¸° êµì²´ ê³¼ì • ëë‚¬ìœ¼ë¯€ë¡œ ë¬´ê¸° êµì²´ ê°€ëŠ¥
    }

    //ë“¤ê³  ìˆë˜ ë¬´ê¸° ë‚´ë¦¬ê¸°
    private void CancelPreWeaponAction()
    {
        switch(currentWeaponType)
        {
            case "GUN":
                theGunController.CancelFineSight(); //ì •ì¡°ì¤€ í•´ì œ
                theGunController.CancelReload(); //ì¬ì¥ì „ í•´ì œ
                GunController.isActivate = false; //í•´ë‹¹ ë¬´ê¸° ë¹„í™œì„±í™”
                break;
            case "HAND":
                HandController.isActivate = false; //í•´ë‹¹ ë¬´ê¸° ë¹„í™œì„±í™”
                if (HandController.currentKit != null)
                    theHandController.Cancel();
                if (QuickSlotController.go_HandItem != null)
                    Destroy(QuickSlotController.go_HandItem);
                break;
             case "AXE":
                AxeController.isActivate = false;
                break;
            case "PICKAXE":
                PickaxeController.isActivate = false;
                break;
        }
    }

    private void WeaponChange(string _type, string _name)
    {

        if(_type == "GUN")
        {
            theGunController.GunChange(gunDictionary[_name]);
        }
        else if(_type == "HAND")
        {
            theHandController.CloseWeaponChange(handDictionary[_name]);
        }
        else if (_type == "AXE")
        {
            theAxeController.CloseWeaponChange(axeDictionary[_name]);
        }
        else if (_type == "PICKAXE")
        {
            thePickaxeController.CloseWeaponChange(pickaxeDictionary[_name]);
        }
    }
}