using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WeaponSway : MonoBehaviour
{
    private Vector3 originPos;  // ê¸°ì¡´ ìœ„ì¹˜. ì›ë˜ ìœ„ì¹˜ ê°’ìœ¼ë¡œ ëŒì•„ê°€ê¸° ìœ„í•´ ë³´ì¡´.
    private Vector3 currentPos;  // í˜„ì¬ ìœ„ì¹˜. ê³„ì† ê³„ì‚°í•´ë‚˜ê°€ë©° ì—…ë°ì´íŠ¸ í•  ê²ƒ.
    public static bool isActivated = true;

    [SerializeField]
    private Vector3 limitPos;  // ì •ì¡°ì¤€ì´ ì•„ë‹ ë•Œ ë¬´ê¸°ê°€ ìµœëŒ€ ì–¼ë§Œí¼ê¹Œì§€ í”ë“¤ë¦´ ìˆ˜ ìˆëŠ”ì§€.
    [SerializeField]
    private Vector3 fineSightLimitPos;  // ì •ì¡°ì¤€ í•  ë•Œ ë¬´ê¸°ê°€ ìµœëŒ€ ì–¼ë§Œí¼ê¹Œì§€ í”ë“¤ë¦´ ìˆ˜ ìˆëŠ”ì§€.
    [SerializeField]
    private Vector3 smoothSway;  // ì´ì´ í”ë“¤ë¦´ ë•Œ ë¶€ë“œëŸ½ê²Œ í”ë“¤ë¦¬ëŠ” ì •ë„.

    [SerializeField]
    private GunController theGunController;  // ğŸ“œGunController.cs ì˜ isFineSightMode ë¥¼ ë°›ì•„ ì˜¤ê¸° ìœ„í•´. ì •ì¡°ì¤€ ìƒíƒœ ì—¬ë¶€ì— ë”°ë¼ í”ë“¤ë¦¼ ì •ë„ê°€ ë‹¤ë¥´ë¯€ë¡œ ì•Œì•„ì•¼ í•¨.

    void Start()
    {
        originPos = this.transform.localPosition;
        currentPos = originPos;
    }

    void Update()
    {
        if (!Inventory.invectoryActivated && isActivated)
            TrySway();
    }

    private void TrySway()
    {
        if (Input.GetAxisRaw("Mouse X") != 0 || Input.GetAxisRaw("Mouse Y") != 0)
            Swaying();
        else
            BackToOriginPos();
    }

    private void Swaying()
    {
        float _moveX = Input.GetAxisRaw("Mouse X");  // -1.0 í˜¹ì€ 0.0 í˜¹ì€ 1.0
        float _moveY = Input.GetAxisRaw("Mouse Y");  // -1.0 í˜¹ì€ 0.0 í˜¹ì€ 1.0

        if(!theGunController.GetFineSightMode())
        {
            currentPos.Set(Mathf.Clamp(Mathf.Lerp(currentPos.x, -_moveX, smoothSway.x), -limitPos.x, limitPos.x),
                        Mathf.Clamp(Mathf.Lerp(currentPos.y, -_moveY, smoothSway.y), -limitPos.y, limitPos.y),
                        originPos.z);
        }
        else
        {
            currentPos.Set(Mathf.Clamp(Mathf.Lerp(currentPos.x, -_moveX, smoothSway.x), -fineSightLimitPos.x, fineSightLimitPos.x),
                        Mathf.Clamp(Mathf.Lerp(currentPos.y, -_moveY, smoothSway.y), -fineSightLimitPos.y, fineSightLimitPos.y),
                        originPos.z);
        }

        transform.localPosition = currentPos;
    }

    private void BackToOriginPos()
    {
        currentPos = Vector3.Lerp(currentPos, originPos, smoothSway.x);
        transform.localPosition = currentPos;
    }
}