using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class Kit  // í•˜ë‚˜ì˜ ì•„ì´í…œì´ ë‹´ê³  ìˆëŠ” ì •ë³´
{
    public string kitName;
    public string kitDescription;
    public string[] needItemName;
    public int[] needItemNumber;
    public GameObject go_Kit_Prefab;
}

public class ComputerKit : MonoBehaviour
{
    [SerializeField]
    private Kit[] kits;  // ì»´í“¨í„°ë¡œ ìƒì„±í•  ìˆ˜ ìˆëŠ” ì•„ì´í…œ ë°°ì—´
    [SerializeField]
    private ComputerToolTip theToolTip;
    [SerializeField] private GameObject go_BaseUI;  // ëª¨ë‹ˆí„° í™”ë©´ ë°°ê²½ ì´ë¯¸ì§€UI

    [SerializeField]
    private Transform tf_ItemAppear; // ì•„ì´í…œ ë‚˜ì˜¤ëŠ” êµ¬ë©ì˜ íŠ¸ëœìŠ¤í¼ ì •ë³´ (Item Appear Pos)

    private bool isCraft = false;  // ì§€ê¸ˆ ì œì‘ ë˜ëŠ” ì¤‘ì¸ì§€. false ì¼ ë•Œë§Œ ì œì‘ ê°€ëŠ¥í•˜ê²Œ í•  ê²ƒ.
    public bool isPowerOn = false; // ì „ì› ì¼œì§„ ìƒíƒœì¸ì§€. ì¤‘ë³µ ì¼œê¸° ë°©ì§€.

    // í•„ìš”í•œ ì»´í¬ë„ŒíŠ¸
    private Inventory theInventory; // ğŸ“œInventory.cs

    private AudioSource theAudio;
    [SerializeField] private AudioClip sound_ButtonClick; // ë²„íŠ¼ í´ë¦­ ì‚¬ìš´ë“œ
    [SerializeField] private AudioClip sound_Beep; // ì•„ì´í…œ ë¶€ì¡±í•˜ì—¬ í‚¤íŠ¸ ìƒì„±ì´ ë¶ˆê°€ëŠ¥í•  ë•Œ ì‚¬ìš´ë“œ
    [SerializeField] private AudioClip sound_Activated; // ì•„ì´í…œ ìƒì„± ì†Œë¦¬
    [SerializeField] private AudioClip sound_Output;  // ì•„ì´í…œ ë‚˜ì˜¤ëŠ” ì†Œë¦¬

    void Start()
    {
        //Cursor.lockState = CursorLockMode.Locked; 
        Cursor.visible = false; 

        theInventory = FindObjectOfType<Inventory>();
        theAudio = GetComponent<AudioSource>();
    }

    void Update()
    {
        if (isPowerOn)
            if (Input.GetKeyDown(KeyCode.Escape))
                PowerOff();
    }

    private void PlaySE(AudioClip _clip) // íš¨ê³¼ìŒ ì¬ìƒ
    {
        theAudio.clip = _clip;
        theAudio.Play();
    }

    public void ClickButton(int _slotNumber) // ìŠ¬ë¡¯ ë²„íŠ¼ í´ë¦­ì‹œ í˜¸ì¶œ
    {
        PlaySE(sound_ButtonClick);  // ì¼ë‹¨ ë²„íŠ¼ í´ë¦­ìŒ ì¬ìƒ
        if(!isCraft)  // í˜„ì¬ ì œì‘ ì¤‘ì´ ì•„ë‹ˆë¼ë©´ ì œì‘ ê°€ëŠ¥
        {
            if (!CheckIngredient(_slotNumber)) // ì¬ë£Œ ìˆëŠ”ì§€ ì²´í¬
                return;

            isCraft = true; // ì¤‘ë³µ ì‹¤í–‰ ë°©ì§€. ì œì‘ ì¤‘ì…ë‹ˆë‹¤.
            UseIngredient(_slotNumber); // ì¬ë£Œ ì‚¬ìš©(ë³´ìœ  ì•„ì´í…œì—ì„œ ì œì‘ì— ì“°ì¸ ê°¯ìˆ˜ë§Œí¼ ì°¨ê°)
            StartCoroutine(CraftCoroutine(_slotNumber)); // í‚¤íŠ¸ ìƒì„±
        }
    }

    private bool CheckIngredient(int _slotNumber)
    {
        for (int i = 0; i < kits[_slotNumber].needItemName.Length; i++)
        {
            if (theInventory.GetItemCount(kits[_slotNumber].needItemName[i]) < kits[_slotNumber].needItemNumber[i])
            {
                PlaySE(sound_Beep);  // ì•„ì´í…œ ì œì‘ ì¬ë£Œ ëª¨ì˜ë¼ì„œ ìƒì„±í•  ìˆ˜ ì—†ëŠ” ê²½ìš° ê²½ê³ ìŒ ì¬ìƒ
                return false;
            }
        }
        return true;
    }

    private void UseIngredient(int _slotNumber)
    {
        for (int i = 0; i < kits[_slotNumber].needItemName.Length; i++)
            theInventory.SetItemCount(kits[_slotNumber].needItemName[i], kits[_slotNumber].needItemNumber[i]);
    }

    IEnumerator CraftCoroutine(int _slotNumber) // ë²„íŠ¼ ëˆ„ë¥´ë©´ 3 ì´ˆ ëŒ€ê¸° í›„ ì•„ì´í…œ ìƒì„±
    {
        PlaySE(sound_Activated); // ì•„ì´í…œ ìƒì„± ì†Œë¦¬ ì¬ìƒ
        yield return new WaitForSeconds(3f);
        PlaySE(sound_Output); // ì•„ì´í…œ ë¹ ì ¸ë‚˜ì˜¤ëŠ” ì†Œë¦¬ ì¬ìƒ 

        Instantiate(kits[_slotNumber].go_Kit_Prefab, tf_ItemAppear.position, Quaternion.identity); // ì•„ì´í…œ ìƒì„±
        isCraft = false;  // ì œì‘ì´ ëë‚¬ìœ¼ë‹ˆ ë‹¤ì‹œ falseë¡œ
    }

    public void ShowToolTip(int _buttonNum)
    {
        theToolTip.ShowToolTip(kits[_buttonNum].kitName, kits[_buttonNum].kitDescription, kits[_buttonNum].needItemName, kits[_buttonNum].needItemNumber);
    }

    public void HideToolTip()
    {
        theToolTip.HideToolTip();
    }

    public void PowerOn() // ğŸ“œActionController ì—ì„œ í˜¸ì¶œ
    {
        GameManager.isOnComputer = true;

        isPowerOn = true;
        go_BaseUI.SetActive(true);
    }

    private void PowerOff()
    {
        GameManager.isOnComputer = false;

        theToolTip.HideToolTip();
        isPowerOn = false;
        go_BaseUI.SetActive(false);
    }
}
