using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class QuickSlotController : MonoBehaviour
{
    // í€µìŠ¬ë¡¯ë“¤ (8ê°œ) 
    [SerializeField] private Slot[] quickSlots; public Slot GetSelectedSlot(){return quickSlots[selectedSlot];}
    [SerializeField] private Transform tf_parent;  // í€µìŠ¬ë¡¯ë“¤ì˜ ë¶€ëª¨ ì˜¤ë¸Œì íŠ¸
    private int selectedSlot;  // ì„ íƒëœ í€µìŠ¬ë¡¯ì˜ ì¸ë±ìŠ¤ (0~7)
    [SerializeField] private GameObject go_SelectedImage;  // ì„ íƒëœ í€µìŠ¬ë¡¯ ì´ë¯¸ì§€

    [SerializeField] private Image[] img_CoolTime;  // í€µìŠ¬ë¡¯ ì¿¨íƒ€ì„ ì´ë¯¸ì§€ë“¤ 
    // ì¿¨íƒ€ì„ ë‚´ìš©
    [SerializeField]
    private float coolTime;  // ì •í•´ì§ ì¿¨íƒ€ì„  [SerializeField]ë¡œ ìœ ë‹ˆí‹° ì¸ìŠ¤í™í„°ì—ì„œ ê²°ì •
    private float currentCoolTime;  // coolTime ì„ ì‹œì‘ì ìœ¼ë¡œ 0 ì´ ë  ë•Œê¹Œì§€ ê°ì†Œ ì—…ëƒ
    private bool isCoolTime;  // í˜„ì¬ ì¿¨íƒ€ì„ ì¤‘ì¸ì§€
    // í€µìŠ¬ë¡¯ ë“±ì¥ ë‚´ìš©
    [SerializeField] private float appearTime;  // í€µìŠ¬ë¡¯ì´ ë‚˜íƒ€ë‚˜ëŠ” ë™ì•ˆì˜ ì‹œê°„
    private float currentAppearTime;
    private bool isAppear;

    [SerializeField]
    private WeaponManager theWeaponManager;
    [SerializeField] private Transform tf_ItemPos;  //ì† ë ì˜¤ë¸Œì íŠ¸. ì† ëì— ì•„ì´í…œì´ ìœ„ì¹˜ë„ë¡
    public static GameObject go_HandItem;   //ì†ì— ë“  ì•„ì´í…œ. staticì¸ ì´ìœ ëŠ” ì´ê±° í•˜ë‚˜ ë°›ì•„ì˜¤ë ¤ê³  ğŸ“œQuickSlotController ë¡œë”©í•˜ëŠ”ê±´ ë‚­ë¹„
    [SerializeField]
    private ItemEffectDatabase theItemEffectDatabase;

    private Animator anim;

    void Start()
    {
        quickSlots = tf_parent.GetComponentsInChildren<Slot>();
        selectedSlot = 0; 
        anim = GetComponent<Animator>();
    }

    void Update()
    {
        TryInputNumber();
        CoolTimeCalc();
        AppearCalc();
    }

    private void TryInputNumber()
    {
        if (Input.GetKeyDown(KeyCode.Alpha1))
            ChangeSlot(0);
        else if (Input.GetKeyDown(KeyCode.Alpha2))
            ChangeSlot(1);
        else if (Input.GetKeyDown(KeyCode.Alpha3))
            ChangeSlot(2);
        else if (Input.GetKeyDown(KeyCode.Alpha4))
            ChangeSlot(3);
        else if (Input.GetKeyDown(KeyCode.Alpha5))
            ChangeSlot(4);
        else if (Input.GetKeyDown(KeyCode.Alpha6))
            ChangeSlot(5);
        else if (Input.GetKeyDown(KeyCode.Alpha7))
            ChangeSlot(6);
        else if (Input.GetKeyDown(KeyCode.Alpha8))
            ChangeSlot(7);
    }

    private void ChangeSlot(int _num)
    {
        SelectedSlot(_num);
        Execute();
    }

    private void SelectedSlot(int _num)
    {
        // ì„ íƒëœ ìŠ¬ë¡¯
        selectedSlot = _num;

        // ì„ íƒëœ ìŠ¬ë¡¯ìœ¼ë¡œ ì´ë¯¸ì§€ ì´ë™
        go_SelectedImage.transform.position = quickSlots[selectedSlot].transform.position;
    }

    public void IsActivatedQuickSlot(int _num)
    {
        if (selectedSlot == _num)
        {
            Execute();
            return;
        }
        if (DragSlot.instance != null)
        {
            if (DragSlot.instance.dragSlot != null)
            {
                if (DragSlot.instance.dragSlot.GetQuickSlotNumber() == selectedSlot)
                {
                    Execute();
                    return;
                }
            }
        }  
    }   

    private void Execute()
    {
        CoolTimeReset();
        AppearReset();

        if (quickSlots[selectedSlot].item != null)
        {
            if (quickSlots[selectedSlot].item.itemType == Item.ItemType.Equipment)
                StartCoroutine(theWeaponManager.ChangeWeaponCoroutine(quickSlots[selectedSlot].item.weaponType, quickSlots[selectedSlot].item.itemName));
            else if (quickSlots[selectedSlot].item.itemType == Item.ItemType.Used || quickSlots[selectedSlot].item.itemType == Item.ItemType.Kit)
                ChangeHand(quickSlots[selectedSlot].item);
            else
                ChangeHand();
        }
        else
        {
            ChangeHand();
        }
    }

    private void ChangeHand(Item _item = null)
    {
        StartCoroutine(theWeaponManager.ChangeWeaponCoroutine("HAND", "ë§¨ì†"));

        if (_item != null)
        {
            StartCoroutine(HandItemCoroutine(_item));
        }
    }

    IEnumerator HandItemCoroutine(Item _item)
    {
        HandController.isActivate = false;
        yield return new WaitUntil(() => HandController.isActivate);  // ë§¨ì† êµì²´ì˜ ë§ˆì§€ë§‰ ê³¼ì •

        if (_item.itemType == Item.ItemType.Kit)
            HandController.currentKit = _item;

        go_HandItem = Instantiate(quickSlots[selectedSlot].item.itemPrefab, tf_ItemPos.position, tf_ItemPos.rotation);
        go_HandItem.GetComponent<Rigidbody>().isKinematic = true;  // ì¤‘ë ¥ ì˜í–¥ X 
        go_HandItem.GetComponent<Collider>().enabled = false;  // ì½œë¼ì´ë” ë” (í”Œë ˆì´ì–´ì™€ ì¶©ëŒí•˜ì§€ ì•Šê²Œ)
        go_HandItem.tag = "Untagged";   // íšë“ ì•ˆë˜ë„ë¡ ë ˆì´ì–´ íƒœê·¸ ë°”ê¿ˆ
        go_HandItem.layer = 6;  // "Weapon" ë ˆì´ì–´ëŠ” int
        go_HandItem.transform.SetParent(tf_ItemPos);
    }

    public void DecreaseSelectedItem()
    {
        theItemEffectDatabase.UseItem(quickSlots[selectedSlot].item);
        quickSlots[selectedSlot].SetSlotCount(-1);

        if (quickSlots[selectedSlot].itemCount <= 0)
            Destroy(go_HandItem);
    }

    private void CoolTimeReset()
    {
        currentCoolTime = coolTime;
        isCoolTime = true;
    }

    private void CoolTimeCalc()
    {
        if (isCoolTime)
        {
            currentCoolTime -= Time.deltaTime;  // 1 ì´ˆì— 1 ì”© ê°ì†Œ

            for (int i = 0; i < img_CoolTime.Length; i++)
                img_CoolTime[i].fillAmount = currentCoolTime / coolTime;

            if (currentCoolTime <= 0)
                isCoolTime = false;
        }
    }

    public bool GetIsCoolTime()
    {
        return isCoolTime;
    }

    private void AppearReset()
    {
        currentAppearTime = appearTime;
        isAppear = true;
        anim.SetBool("Appear", isAppear);
    }

    private void AppearCalc()
    {
        if (Inventory.invectoryActivated)  // ì¸ë²¤í† ë¦¬ ì¼œì ¸ìˆì„ ë• í€µìŠ¬ë¡¯ë„ ëŠ˜ í™œì„±í™”
            AppearReset();
        else  // ì¸ë²¤í† ë¦¬ê°€ ì¼œì ¸ ìˆì§€ ì•Šì„ë•Œë§Œ ì¿¨íƒ€ì„ ê¹ì•„ì•¼ í•¨
        {
            if (isAppear)
            {
                currentAppearTime -= Time.deltaTime; // 1ì´ˆì— 1ê°ì†Œ
                if (currentAppearTime <= 0)
                {
                    isAppear = false;
                    anim.SetBool("Appear", isAppear);
                }
            }
        }
        
    }
}